version: "3.4"

services:

  api:
    build:
      context: ..
      dockerfile: ./devops/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "../app:/work"
    environment:
      - DATABASE_URL=postgresql://api:Abc@devops-db-1:5432/main_db
      - PYTHONPATH=/work
    depends_on:
      - db

  db:
    image: postgres:10.1-alpine
    restart: always
    volumes:
      - "main_db:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=Abc
      - POSTGRES_DB=main_db

volumes:
  main_db: